### ISSUE TITLE
CRYOSPARC_SLACK_WEBHOOK_URL value

### ISSUE THREAD

**Issue by ccgauvin94** [marinegor/ntfy_cryosparc#1]
Hi,
What should the CRYOSPARC_SLACK_WEBHOOK_URL be pointing to? localhost:8000? Just not clear to me from the Readme, what this is.

**Comment by marinegor** [comment]
Hi @ccgauvin94, in my `config.sh` I have this:

```bash
export CRYOSPARC_SLACK_WEBHOOK_URL="http://localhost:8000"
```

**Comment by marinegor** [comment]
I updated the readme accordingly -- please tell me if it works for you.

**Comment by ccgauvin94** [comment]
Thanks!  Looks like I wasn't far off. I will give it a shot. Probably won't be able to test for a few days due to running jobs.

**Comment by marinegor** [comment]
Ok, I see. You can also re-run one of the old jobs like "Import movies" or even "Select 2D classes" to test it. 

E M

**Comment by ccgauvin94** [comment]
Sorry - meant I can't restart my CryoSPARC instance without really annoying a bunch of people, so I have to wait for the next maintenance window.

**Comment by ccgauvin94** [comment]
Everything is working great with that config! Thanks for putting this all together. :)
